aws_pem           = "../RT_lab.pem"
aws_region        = "eu-central-1"
#aws_creds_file    = "~/.aws/credentials"
#aws_profile       = "redteamlab"
ssh_key           = "RT_lab"
alt_rdp_source_ip = "123.123.123.123/32"
win_username      = "Administrator"
win_password      = "P@ssword123"