- name: Change the hostname to member1
  ansible.windows.win_hostname:
    name: member1
  register: res
  
- name: reboot | Rebooting Server
  win_reboot:
    reboot_timeout_sec: 300
    shutdown_timeout: 300
  when: res.reboot_required
