- name: Deploy Workstation Threat Optics
  ansible.windows.win_shell: C:\Users\Administrator\Downloads\WS-optics.ps1 >> C:\Users\Administrator\Downloads\somelog.txt
  ignore_errors: yes

- name : Final Reboot 
  win_reboot: 